#!/bin/bash

# สำหรับ Sunhanut เพื่อสร้าง Azure VMScale Set เพื่อทำ PoC for SiteCore Project 
sleep 20s
apt-get update
apt-get install stress -y
apt-get install apache2 -y
ufw allow 'Apache Full'
ufw allow 'OpenSSH'
ufw enable
